### ISSUE TITLE
 ModuleNotFoundError: No module named 'fedml.data.fednlp'

### ISSUE THREAD

**Issue by Luoyang144** [FedML-AI/FedML#376] opened 2022-07-16 08:15 UTC
When running the example of TEXT CLASSIFICATION in fednlp.
```bash run_simulation.sh 1```
Encounter an error
![image](https://user-images.githubusercontent.com/63402979/179346569-21317944-b427-48ad-821f-6a3ab6add2a9.png)
Is this caused by fedml or what else? All dependency is installed. Link: https://github.com/FedML-AI/FedML/tree/master/python/app/fednlp

**Comment by chaoyanghe** [comment] 2022-07-16 13:58
@Luoyang144 Please provide your context info by typing "fedml env".

I guess you only need to install the latest FedML. Check the guidance at https://doc.fedml.ai/starter/installation.html

**Comment by Luoyang144** [comment] 2022-07-17 02:04
Here is the context after typing ```fedml env```，I just use ```pip install fedml``` to install FedML, is this the latest version?
![image](https://user-images.githubusercontent.com/63402979/179380823-fa460fe6-6223-4178-932f-b6f3f29ffff9.png)
By the way, I install 0.7.208 which is the latest version in PyPI but the same error occured too.

**Comment by zuluzazu** [comment] 2022-07-17 04:41
@Luoyang144 Can you check whether you are using the correct version of python in run_simulation.sh? So basically are you running the python file using python3.8 or python2 by mistake? Can you send me a screenshot of run_simulation.sh you are using?

**Comment by chaoyanghe** [comment] 2022-07-17 05:01
@Luo

> Here is the context after typing `fedml env`，I just use `pip install fedml` to install FedML, is this the latest version? ![image](https://user-images.githubusercontent.com/63402979/179380823-fa460fe6-6223-4178-932f-b6f3f29ffff9.png) By the way, I install 0.7.208 which is the latest version in PyPI but the same error occured too.

I just submitted a fix. Please have a try again. The latest version is 0.7.210

**Comment by Luoyang144** [comment] 2022-07-17 08:30
@[zuluzazu](https://github.com/zuluzazu)I am using python 3.8 which is the installation gudiance in this link: https://github.com/FedML-AI/FedML/tree/master/python/app/fednlp
```conda create -n fednlp python=3.8```
I tried to change python=3.7 and reinstall the environment, though there are still bugs, this bug didn't occur. So this may caused by python3.8? (or fedml version) 
So maybe you can change the install gudiance in below link, the requirement.txt there can't work so well in python3.7, though it didn't trouble me.

**Comment by zuluzazu** [comment] 2022-07-17 08:33
@Luoyang144 Please follow the exact steps in README file now. It will work. We have resolved the issue. Please check. Please use python3.8 and not any other version

**Comment by zuluzazu** [comment] 2022-07-17 08:39
@Luoyang144 The issue is resolved in fedml version 0.7.210

**Comment by Luoyang144** [comment] 2022-07-18 04:04
Thank you for contribution, shall I close this issue? I remember it had been closed yesterday.

**Closed** 2022-07-18 07:10 UTC
