### ISSUE TITLE
FedAvg accuracy stucks under 50 

### ISSUE THREAD

**Issue by AbdulMoqeet** [FedML-AI/FedML#115] opened 2021-04-22 01:46 UTC
I am training Fedavg to get the benchmark accuracy with the given parameters. But, the accuracy is stuck under 50. 

Here is all my code: 

`!git clone https://github.com/FedML-AI/FedML`

`cd /content/FedML/fedml_experiments/standalone/fedavg`

`!python main_fedavg.py --model mobilenet --dataset cifar10 --data_dir ./../../../data/cifar10 --partition_method hetero --comm_round 100 --epochs 20 --batch_size 64 --lr 0.001`

I suppose to get over 80% accuracy at least according to these benchmark results.  

https://wandb.ai/automl/fedml/runs/390hdz0e

**Comment by hangxu0304** [comment] 2021-04-22 10:08
Same issue here!!! I have also tried ResNet56 on Cifar10 with given hyper-parameters, but only got 41% test accuracy with adam optimizer and 20% test accuracy with sgd optimizer.

**Comment by chaoyanghe** [comment] 2021-04-23 21:38
Our result is based on distributed version. You are running on standalone version. Let me check what's the code difference here.

**Comment by hangxu0304** [comment] 2021-04-24 07:13
> Same issue here!!! I have also tried ResNet56 on Cifar10 with given hyper-parameters, but only got 41% test accuracy with adam optimizer and 20% test accuracy with sgd optimizer.

Actually I was running the distributed version here. Here is my cmd:
```
sh run_fedavg_distributed_pytorch.sh 10 10 resnet56 hetero 100 20 64 0.001 cifar10 "./../../../data/cifar10" adam MPI grpc_ipconfig_test.csv 1
```
```
sh run_fedavg_distributed_pytorch.sh 10 10 resnet56 hetero 100 20 64 0.001 cifar10 "./../../../data/cifar10" sgd MPI grpc_ipconfig_test.csv 1
```

**Comment by wizard1203** [comment] 2021-04-25 07:58
@AbdulMoqeet @hangxu0304 Hi, could you have another try with a smaller number of local epochs, e.g. E=1. The large epochs usually make training harder to converge.

**Comment by hangxu0304** [comment] 2021-04-25 08:31
> @AbdulMoqeet @hangxu0304 Hi, could you have another try with a smaller number of local epochs, e.g. E=1. The large epochs usually make training harder to converge.

Yes, I have also tested Epoch=1 for ResNet56 on Cifar10. Smaller local epochs (e=1) indeed gives better accuracy (57% after 100 rounds), but it is still far away from the benchmark result (87% after 100 rounds).  You can check the details in my [wandb report](https://wandb.ai/hangxu0a/fedml/reports/FedML-benchmark-results--Vmlldzo2MzcwODE?accessToken=bbj0sun4yq8uf7xx7al5rv3v099gx0hwp7ayuw3mu60ri3nhclweyspzjmm972yv).

**Comment by hangxu0304** [comment] 2021-04-25 12:53
I tried the code from an early [commit](https://github.com/FedML-AI/FedML/tree/50d8a45d27675343a7b05a9b31279f6764d3f2ad), and the accuracy can be reproduced. I guess there might be some inconsistency between the early and latest commit. @chaoyanghe

**Comment by AbdulMoqeet** [comment] 2021-04-26 01:50
@hangxu0304 Could you please share hyperparameters or **wandb report** ? The default hyperparameters (client numbers) are different in both scripts.  There is additional parameter (# of local points) in earlier commit.

**Comment by chaoyanghe** [comment] 2021-04-26 04:30
@hangxu0304 I see. Could you help to figure out the difference?

**Comment by hangxu0304** [comment] 2021-04-26 07:07
> @hangxu0304 Could you please share hyperparameters or **wandb report** ? The default hyperparameters (client numbers) are different in both scripts. There is additional parameter (# of local points) in earlier commit.

I was running the distributed version. First, you need to check out this [commit](https://github.com/FedML-AI/FedML/tree/50d8a45d27675343a7b05a9b31279f6764d3f2ad).
Then:
```
cd FedML/fedml_experiments/distributed/fedavg

sh run_fedavg_distributed_pytorch.sh 4 3 resnet56 hetero 2000 1 64 0.001 cifar10 ./../../../data/cifar10
```
```
/main_fedavg.py --gpu_server_num 4 --gpu_num_per_server 3 --model resnet56 --dataset cifar10 --data_dir ./../../../data/cifar10 --partition_method hetero --client_number 11 --comm_round 2000 --epochs 1 --batch_size 64 --lr 0.001
```
Other parameters (e.g. local points) are kept as default.

The result is shown on the right side in this [report](https://wandb.ai/hangxu0a/fedml/reports/FedML-benchmark-results--Vmlldzo2MzcwODE).

**Comment by AbdulMoqeet** [comment] 2021-04-27 03:19
Great! Thanks for sharing. The report is no longer available.  

I've also got the Cifar10 results with epoch 1. 

Now, trying to reproduce the CIFAR100.

**Comment by wizard1203** [comment] 2021-04-29 08:55
@hangxu0304 @AbdulMoqeet Hi, I find some possible reasons for this bug:
Please check these codes:
Original version:  https://github.com/FedML-AI/FedML/blob/50d8a45d27675343a7b05a9b31279f6764d3f2ad/fedml_api/standalone/fedavg/fedavg_trainer.py#L45

Current version: https://github.com/FedML-AI/FedML/blob/8ccc24cf2c01b868988f5d5bd65f1666cf5526bc/fedml_api/standalone/fedavg/fedavg_api.py#L64

In the original version, the global model is deepcopied and loaded into clients.
However, in the current version, the local client just load the global model (without deepcopy). So maybe the local training in every client will update the global model ?

I'm not completely sure that the bug is cased by this. Could you please change the current codes (make a deepcopy of global model) and to see if the result is correct?

**Comment by hangxu0304** [comment] 2021-04-29 11:31
This might be true for the standalone version. But in distributed version, each client only needs to update this global model and then upload it to the server. My previous results showed that distributed version also has this low accuracy issue.

**Comment by wizard1203** [comment] 2021-04-29 11:35
> This might be true for the standalone version. But in distributed version, each client only needs to update this global model and then upload it to the server. My previous results showed that distributed version also has this low accuracy issue.

Do you mean you cannot get similar accuracy with the benchmark results of distributed version, even same hyper-parameters?

**Comment by hangxu0304** [comment] 2021-04-29 11:38
> > @AbdulMoqeet @hangxu0304 Hi, could you have another try with a smaller number of local epochs, e.g. E=1. The large epochs usually make training harder to converge.
> 
> Yes, I have also tested Epoch=1 for ResNet56 on Cifar10. Smaller local epochs (e=1) indeed gives better accuracy (57% after 100 rounds), but it is still far away from the benchmark result (87% after 100 rounds). You can check the details in my [wandb report](https://wandb.ai/hangxu0a/fedml/reports/FedML-benchmark-results--Vmlldzo2MzcwODE?accessToken=bbj0sun4yq8uf7xx7al5rv3v099gx0hwp7ayuw3mu60ri3nhclweyspzjmm972yv).

Right. Please check my previous comments.

**Comment by wizard1203** [comment] 2021-04-29 11:53
@hangxu0304 
For the distributed implementation, I find these differences:

https://github.com/FedML-AI/FedML/blob/8ccc24cf2c01b868988f5d5bd65f1666cf5526bc/fedml_api/standalone/fedavg/my_model_trainer_classification.py#L44

https://github.com/FedML-AI/FedML/blob/50d8a45d27675343a7b05a9b31279f6764d3f2ad/fedml_api/distributed/fedavg/FedAVGTrainer.py#L29

In original version, there is no grad clip. However, in current version, there is a grad clip. This could be one possible reason. And other things seem to be the same.

**Comment by wizard1203** [comment] 2021-04-29 12:29
I have ran out some new experiments results, verifying that the lack of deepcopy of global model in standalone will indeed induce bugs. But I cannot merge my codes to this version now because I'm waiting for my other experiment results for some new papers. Maybe you can firstly fix them by yourselves for current usage @chaoyanghe @AbdulMoqeet .

**Comment by chaoyanghe** [comment] 2021-05-03 16:38
@AbdulMoqeet @hangxu0304 @wizard1203 Hi All, what's the final conclusion?

**Comment by chaoyanghe** [comment] 2021-05-03 19:16
> Great! Thanks for sharing. The report is no longer available.
> 
> I've also got the Cifar10 results with epoch 1.
> 
> Now, trying to reproduce the CIFAR100.

Hi Abdul, have you reproduced the result of CIFAR-100 with local epoch = 1?

**Comment by chaoyanghe** [comment] 2021-05-03 19:36
> > Same issue here!!! I have also tried ResNet56 on Cifar10 with given hyper-parameters, but only got 41% test accuracy with adam optimizer and 20% test accuracy with sgd optimizer.
> 
> Actually I was running the distributed version here. Here is my cmd:
> 
> ```
> sh run_fedavg_distributed_pytorch.sh 10 10 resnet56 hetero 100 20 64 0.001 cifar10 "./../../../data/cifar10" adam MPI grpc_ipconfig_test.csv 1
> ```
> 
> ```
> sh run_fedavg_distributed_pytorch.sh 10 10 resnet56 hetero 100 20 64 0.001 cifar10 "./../../../data/cifar10" sgd MPI grpc_ipconfig_test.csv 1
> ```

Hi, that you got low accuracy because you set ci=1 (the last hyper-parameter as your scrip shows), which is used for the sanity check. When ci=1, we will skip a long test time as follows:

```
    def test_on_server_for_all_clients(self, round_idx):
        if self.trainer.test_on_the_server(self.train_data_local_dict, self.test_data_local_dict, self.device, self.args):
            return

        if round_idx % self.args.frequency_of_the_test == 0 or round_idx == self.args.comm_round - 1:
            logging.info("################test_on_server_for_all_clients : {}".format(round_idx))
            train_num_samples = []
            train_tot_corrects = []
            train_losses = []
            for client_idx in range(self.args.client_num_in_total):
                # train data
                metrics = self.trainer.test(self.train_data_local_dict[client_idx], self.device, self.args)
                train_tot_correct, train_num_sample, train_loss = metrics['test_correct'], metrics['test_total'], metrics['test_loss']
                train_tot_corrects.append(copy.deepcopy(train_tot_correct))
                train_num_samples.append(copy.deepcopy(train_num_sample))
                train_losses.append(copy.deepcopy(train_loss))

                """
                Note: CI environment is CPU-based computing. 
                The training speed for RNN training is to slow in this setting, so we only test a client to make sure there is no programming error.
                """
                if self.args.ci == 1:
                    break

```

**Comment by hangxu0304** [comment] 2021-05-04 04:59
> @AbdulMoqeet @hangxu0304 @wizard1203 Hi All, what's the final conclusion?

I'm trying to check whether gradient clipping is the cause. The experiment is still running. Let's see.

**Comment by AbdulMoqeet** [comment] 2021-05-04 05:08
> > Great! Thanks for sharing. The report is no longer available.
> > I've also got the Cifar10 results with epoch 1.
> > Now, trying to reproduce the CIFAR100.
> 
> Hi @AbdulMoqeet, have you reproduced the result of CIFAR-100 with local epoch = 1?

@chaoyanghe Due to limitation of resources, I was trying on Colab. I have used following command with epochs 20. 

`./main_fedavg.py --gpu 0 --dataset cifar100 --data_dir ./../../../data/cifar100 --model mobilenet --partition_method hetero --client_number 10 --comm_round 200 --epochs 20 --batch-size 64 --lr 0.001`

It achieves reasonable accuracy given that it crashes. 

Here is the report:
https://wandb.ai/amuqeet/fedml/runs/htvgqh83

**Comment by chaoyanghe** [comment] 2021-05-04 05:10
> > @AbdulMoqeet @hangxu0304 @wizard1203 Hi All, what's the final conclusion?
> 
> I'm trying to check whether gradient clipping is the cause. The experiment is still running. Let's see.

Have you changed CI to 0

**Comment by hangxu0304** [comment] 2021-05-04 05:11
Yes.

**Comment by hangxu0304** [comment] 2021-05-04 05:23
@chaoyanghe I think CI only affects the training accuracy, not the test accuracy, right?

**Comment by chaoyanghe** [comment] 2021-05-04 05:53
> @chaoyanghe I think CI only affects the training accuracy, not the test accuracy, right?

Both. Let's wait for your result.

**Comment by hangxu0304** [comment] 2021-05-04 21:00
![image](https://user-images.githubusercontent.com/52653060/117068499-0775d700-ad34-11eb-82ec-943de166399c.png)
@chaoyanghe The left one is the latest commit without gradient clipping, and the right one is the old commit. Both use the same hyper-parameter settings as FedML ResNet56 Cifar10 benchmark. You can check the details in my [wandb](https://wandb.ai/hangxu0a/fedml/reports/FedML-benchmark-results--Vmlldzo2MzcwODE?accessToken=bbj0sun4yq8uf7xx7al5rv3v099gx0hwp7ayuw3mu60ri3nhclweyspzjmm972yv).

**Comment by chaoyanghe** [comment] 2021-05-04 22:13
> ![image](https://user-images.githubusercontent.com/52653060/117068499-0775d700-ad34-11eb-82ec-943de166399c.png)
> @chaoyanghe The left one is the latest commit without gradient clipping, and the right one is the old commit. Both use the same hyper-parameter settings as FedML ResNet56 Cifar10 benchmark. You can check the details in my [wandb](https://wandb.ai/hangxu0a/fedml/reports/FedML-benchmark-results--Vmlldzo2MzcwODE?accessToken=bbj0sun4yq8uf7xx7al5rv3v099gx0hwp7ayuw3mu60ri3nhclweyspzjmm972yv).

I cannot access your report.

**Comment by hangxu0304** [comment] 2021-05-05 12:36
@chaoyanghe That's strange. I already shared this report, and I can view it without login. Anyway, you can check the results I posted above. I'm wondering if you can obtain a good accuracy by running the latest code on your cluster. And also the result by running old commit doesn't show the same convergence as your benchmark result.

**Comment by AbdulMoqeet** [comment] 2021-05-06 00:53
Detailed report cannot be accessed as project is set to private. But, only these two graphs (reports) are accessible.

**Comment by chaoyanghe** [comment] 2021-05-06 04:15
@hangxu0304 I reproduced the same result with the latest code in both standalone and distributed version. I am not sure what's the difference. If you could make your reports public, it will be very helpful. Thanks in advance.

**Comment by hangxu0304** [comment] 2021-05-07 00:47
@chaoyanghe  Sure. I made it public now, please check [here](https://wandb.ai/hangxu0a/fedml-test/reports/FedML-benchmark-results--Vmlldzo2NjkzMDQ).

**Comment by 11asdad** [comment] 2021-05-17 13:13
@chaoyanghe Hi,I found myself in a similar situation, and a simpler one, After I downloaded fedml project without changes,I directly copied the code in the CNN + fedmnist example given in the readme of "……/standalone/fedavg": https://wandb.ai/automl/fedml/runs/3lv4gmpz/overview?workspace=user-
but the result is quite different and the loss rate is very high. This is my result: https://wandb.ai/automl/fedml/runs/35t97few/overview?workspace=user-
And in the  situation which is fedcifar100 + resnet18 ,the result also is such, I copied the code in https://wandb.ai/automl/fedml/runs/1canbwed/overview?workspace=user-  , and this is my results: https://wandb.ai/automl/fedml/runs/zcupgmt8/overview?workspace=user-

@chaoyanghe 您好，我也遇到了类似的情况，并且没有他们的那么复杂，很奇怪。我克隆到本地后尚未对源码做任何修改，直接参照readme试着运行standalone中的示例指令（以确保超参数相同），发现结果相差的很离谱，都是acc低一些，而loss高的离谱甚至大于1。
我尝试了cnn+fedmnist和18层残差+fedcifar100两种情况均如此，并且我检查了代码，确认seed是写死的。
cnn+fedmnist的参考:https://wandb.ai/automl/fedml/runs/3lv4gmpz/overview?workspace=user-
我的结果：https://wandb.ai/automl/fedml/runs/35t97few/overview?workspace=user-
18层残差+fedcifar100的参考：https://wandb.ai/automl/fedml/runs/1canbwed/overview?workspace=user-
我的结果：https://wandb.ai/automl/fedml/runs/zcupgmt8/overview?workspace=user-

**Comment by chaoyanghe** [comment] 2021-05-17 16:28
@11asdad Thanks for your feedback. we mainly maintained distributed version, everything works well. The result is reported by distributed version. 

For the issue you mentioned at standalone version, could you help to compare its difference from the distributed one?

**Comment by chaoyanghe** [comment] 2021-05-17 16:31
the benchmarking hyper-parameters are here:
https://github.com/FedML-AI/FedML/tree/master/benchmark

@11asdad

**Comment by AbdulMoqeet** [comment] 2021-05-18 00:11
@11asdad Try the previous commit mentioned above, it shows better performance.

**Comment by 11asdad** [comment] 2021-05-20 00:35
@chaoyanghe @AbdulMoqeet Thank you. I have modified the parameters according to the benchmark mentioned above, and the result is a little normal. There may not be a big problem with the code. maybe just the Readme is not updated synchronously. I'm trying to see the effect in a distributed situation to find out, but I'm running into some configuration problems and I'm stuck.

**Comment by mmendiet** [comment] 2021-05-21 16:24
Hello everyone!

I have also encountered similar issues with FedAvg (distributed). I conducted some experiments with ResNet56 on CIFAR100 non-IID and found the following.
I checked-out the branch from the benchmark wandb run [here](https://wandb.ai/automl/fedml/runs/28zmqj1z/overview). On 8 RTX2080ti GPUs, I was able to reproduce the results almost exactly (I got 64.56% and the benchmark reports 64.7%) (see [here](https://wandb.ai/mmendiet/FedML/reports/FedAvg-ResNet56-CIFAR100-Experiments--Vmlldzo3MTI1MzA) for all my results I will mention in this post).
In the current FedML master (as of May 15th, 2021 when I cloned it), I was getting much lower accuracy. I looked for differences between these branches and noticed 3 things:

1. There is a grad clip in the current version (as others have previously mentioned) [[code](https://github.com/FedML-AI/FedML/blob/400072ef5daa9a9ca0f205ff3a90ccf13f975729/fedml_api/standalone/fedavg/my_model_trainer_classification.py#L44)], but not in the old version.
2. model.zero_grad() [[code](https://github.com/FedML-AI/FedML/blob/400072ef5daa9a9ca0f205ff3a90ccf13f975729/fedml_api/standalone/fedavg/my_model_trainer_classification.py#L38)] is used versus optimizer.zero_grad() in the old version.
3. Weight decay is 0.001 [[code](https://github.com/FedML-AI/FedML/blob/400072ef5daa9a9ca0f205ff3a90ccf13f975729/fedml_experiments/distributed/fedavg/main_fedavg.py#L87), and [here](https://github.com/FedML-AI/FedML/blob/400072ef5daa9a9ca0f205ff3a90ccf13f975729/fedml_api/standalone/fedavg/my_model_trainer_classification.py#L31)] in the new version by default but is hard-coded in the old version to 0.0001 for Adam.

Notice that although (1) and (2) are from the standalone API files, the standalone classification trainer is used in the current version for the distributed code also [import seen [here](https://github.com/FedML-AI/FedML/blob/400072ef5daa9a9ca0f205ff3a90ccf13f975729/fedml_api/distributed/fedavg/FedAvgAPI.py#L8)]. It appears they were merged sometime a while back. Making these changes I was able to get decent results on both 4 and 8 GPUs (about 1% lower than the old code in both cases). I’m not sure if (2) actually made much difference but I didn't test it fully in isolation. (1) and (3) definitely make a difference though.
.
I also looked into reproducing the FedAvg results reported in the FedGKT paper (this was my primary interest to begin with). These use 16 clients rather than 10 and 200 rounds rather than 100. With the original benchmark FedAvg code, I reproduced the results closely (reported 63.78% and I got 64.23%). However, in the current code with my modifications, I was still 2% lower (~62%).
There still must be some differences, but since the time of the original benchmark code, it appears many changes in the underlying code have been made. I have not been able to determine the exact cause of the last 1-2% discrepancy. Has anyone found other potential causes for this 1-2% difference?

**Comment by 11asdad** [comment] 2021-07-09 21:41
@mmendiet hello，I noticed a difference in the client emulation between the old version and the new version. The new version has a new parameter "client_num_per_round", whereas in the old version this is defined directly as the return value of "mpi4py.MPI.COMM_world.get_size () "(which I guess is 8 in your environment). This might make some difference.
Could you please share your revised new version of the code? The old version is inconvenient to use. Thank you very much.

**Comment by chaoyanghe** [comment] 2022-08-17 00:12
@11asdad @mmendiet @AbdulMoqeet our new version is released. Please check the latest repo

**Closed** 2022-08-17 00:12 UTC
